# Generated by Django 4.2.7 on 2025-05-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.CharField(default='Welcome!', max_length=255)),
                ('show_sales_summary', models.BooleanField(default=True)),
                ('show_hr_summary', models.BooleanField(default=True)),
                ('show_warehouse_summary', models.BooleanField(default=True)),
            ],
        ),
    ]
