name: CI/CD for Django (no Nginx/Gunicorn)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd clothes_shop_erp
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py migrate
          pkill -f runserver || true
          nohup python3 manage.py runserver 0.0.0.0:8000 > log.txt 2>&1 &
